"""empty message

Revision ID: 47dedd19c43a
Revises: bb6528819472
Create Date: 2024-06-14 13:07:57.312433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47dedd19c43a'
down_revision: Union[str, None] = 'bb6528819472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('korname', sa.String(), nullable=False),
    sa.Column('sofascoredid', sa.String(), nullable=False),
    sa.Column('familyname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    # ### end Alembic commands ###
