"""empty message

Revision ID: 96e034cce83c
Revises: 252eea91e0ae
Create Date: 2024-06-25 06:20:19.583527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e034cce83c'
down_revision: Union[str, None] = '252eea91e0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('nation_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'nation_code')
    # ### end Alembic commands ###
